--inserts  
INSERT INTO TBL_SUPER_HEROE (NOMBRE_HEROE, SUPER_PODER) VALUES ('Batman', 'Dinero');
INSERT INTO TBL_SUPER_HEROE (NOMBRE_HEROE, SUPER_PODER) VALUES ('Superman', 'Volar');
INSERT INTO TBL_SUPER_HEROE (NOMBRE_HEROE, SUPER_PODER) VALUES ('Flash', 'Correr');
INSERT INTO TBL_SUPER_HEROE (NOMBRE_HEROE, SUPER_PODER) VALUES ('Green Arrow', 'Mallas');